import type { Kpi } from "./types";

export type KpiTemplate = Omit<Kpi, "id" | "organization_id" | "owner" | "steward" | "status" | "version" | "notes" | "created_at" | "updated_at"> & { key: string };

/** Definições de referência para empresas de médio porte (núcleo universal + módulos por setor).
 *  Servem de ponto de partida — o responsável por cada KPI deve validar as premissas. */
export const KPI_LIBRARY: KpiTemplate[] = [
  {
    key: "faturamento_liquido", name: "Faturamento líquido", code: "COM-001", domain: "comercial",
    definition: "Receita de vendas após devoluções, cancelamentos e descontos incondicionais.",
    business_question: "Quanto vendemos de fato no período?",
    formula: "Σ valor faturado − Σ devoluções − Σ cancelamentos − Σ descontos incondicionais",
    numerator: "Valor faturado líquido", denominator: null, unit: "R$", granularity: "Dia × loja/canal × SKU", frequency: "Diária",
    direction: "maior_melhor", target: null,
    assumptions: "Data de referência = data de emissão da NF. Devolução abate no mês da devolução (não no da venda).",
    exclusions: "Bonificações, remessas, transferências entre filiais.",
    source_tables: "ERP: notas fiscais de saída (itens) + notas de devolução", lineage: "ERP → bronze.nf_itens → prata.vendas → ouro.fato_vendas",
    quality_checks: "Conciliação mensal com contábil (tolerância 0,5%); dias sem faturamento por loja.", consumers: "Diretoria, Comercial, FP&A",
  },
  {
    key: "ticket_medio", name: "Ticket médio", code: "COM-002", domain: "comercial",
    definition: "Valor médio por pedido/cupom.", business_question: "Quanto cada cliente gasta por compra?",
    formula: "Faturamento líquido ÷ nº de pedidos (ou cupons) distintos",
    numerator: "Faturamento líquido", denominator: "Pedidos distintos", unit: "R$", granularity: "Dia × loja/canal", frequency: "Diária",
    direction: "maior_melhor", target: null,
    assumptions: "Pedido cancelado integralmente não conta no denominador.", exclusions: "Vendas B2B atacado (distorcem a média) — reportar separado.",
    source_tables: "ERP/PDV: cabeçalho de pedidos + fato_vendas", lineage: null, quality_checks: "Pedidos com valor zero ou negativo.", consumers: "Comercial, Marketing",
  },
  {
    key: "margem_bruta", name: "Margem bruta", code: "FIN-001", domain: "financeiro",
    definition: "Percentual da receita líquida que sobra após o custo das mercadorias vendidas.",
    business_question: "Estamos vendendo com lucro por produto/canal?",
    formula: "(Receita líquida − CMV) ÷ Receita líquida",
    numerator: "Receita líquida − CMV", denominator: "Receita líquida", unit: "%", granularity: "Mês × categoria × canal", frequency: "Mensal",
    direction: "maior_melhor", target: null,
    assumptions: "CMV pelo custo médio do ERP no momento da venda. Definir se inclui frete de entrada (landed cost).",
    exclusions: "Receitas não operacionais.", source_tables: "ERP: fato_vendas + custo médio por SKU (FP&A)", lineage: null,
    quality_checks: "SKUs com custo zero ou custo > preço; variação de custo > 20% mês a mês.", consumers: "Diretoria, FP&A, Comercial",
  },
  {
    key: "gmroi", name: "GMROI", code: "FIN-002", domain: "financeiro",
    definition: "Retorno da margem bruta sobre o investimento médio em estoque.",
    business_question: "Cada real parado em estoque gera quanto de margem?",
    formula: "Margem bruta (R$) ÷ Estoque médio a custo (R$)",
    numerator: "Margem bruta R$", denominator: "Estoque médio a custo", unit: "x", granularity: "Mês × categoria", frequency: "Mensal",
    direction: "maior_melhor", target: null, assumptions: "Estoque médio = média dos saldos diários (ou início+fim/2 se não houver diário).",
    exclusions: null, source_tables: "fato_vendas + fato_estoque_diario", lineage: null, quality_checks: null, consumers: "Diretoria, Compras",
  },
  {
    key: "acuracidade_inventario", name: "Acuracidade de inventário", code: "EST-001", domain: "estoque",
    definition: "Percentual de posições/SKUs cujo saldo em sistema bate com a contagem física.",
    business_question: "Podemos confiar no saldo que o sistema mostra?",
    formula: "Nº de SKUs-posição sem divergência ÷ Nº de SKUs-posição contados",
    numerator: "SKUs sem divergência", denominator: "SKUs contados", unit: "%", granularity: "Contagem × CD/loja × curva ABC", frequency: "Por ciclo de contagem",
    direction: "maior_melhor", target: "≥ 98% curva A",
    assumptions: "Divergência = diferença acima da tolerância definida (ex.: 0 un. para curva A).", exclusions: "SKUs em trânsito ou bloqueados.",
    source_tables: "WMS: contagens cíclicas × saldo sistema no momento da contagem", lineage: null,
    quality_checks: "Contagens sem registro de saldo sistema congelado.", consumers: "Logística, Controladoria",
  },
  {
    key: "ruptura", name: "Ruptura", code: "EST-002", domain: "estoque",
    definition: "Percentual de SKUs ativos sem estoque disponível para venda.",
    business_question: "Quanto do sortimento o cliente não encontra?",
    formula: "SKUs ativos com estoque disponível ≤ 0 ÷ SKUs ativos (por dia, média do período)",
    numerator: "SKUs sem estoque", denominator: "SKUs ativos", unit: "%", granularity: "Dia × loja/CD × SKU", frequency: "Diária",
    direction: "menor_melhor", target: null, assumptions: "SKU ativo = comercializável e não descontinuado. Estoque disponível = saldo − reservas.",
    exclusions: "SKUs sazonais fora de temporada.", source_tables: "fato_estoque_diario + dim_produto (status)", lineage: null,
    quality_checks: "Saldos negativos; SKUs sem status definido.", consumers: "Comercial, Compras, E-commerce",
  },
  {
    key: "cobertura_estoque", name: "Cobertura de estoque (dias)", code: "EST-003", domain: "estoque",
    definition: "Quantos dias o estoque atual sustenta a venda média projetada.", business_question: "Quando vamos ficar sem produto?",
    formula: "Estoque disponível (un.) ÷ Venda média diária (un.) dos últimos N dias",
    numerator: "Estoque disponível", denominator: "Venda média diária", unit: "dias", granularity: "SKU × local", frequency: "Diária",
    direction: "faixa", target: "Entre lead time + estoque de segurança e 60 dias",
    assumptions: "N = 30 dias; dias em ruptura são excluídos da média para não subestimar a demanda.", exclusions: null,
    source_tables: "fato_estoque_diario + fato_vendas", lineage: null, quality_checks: null, consumers: "Compras, Comercial",
  },
  {
    key: "giro_estoque", name: "Giro de estoque", code: "EST-004", domain: "estoque",
    definition: "Quantas vezes o estoque se renova no período.", business_question: "O capital em estoque está girando?",
    formula: "CMV do período ÷ Estoque médio a custo", numerator: "CMV", denominator: "Estoque médio a custo", unit: "x", granularity: "Mês × categoria", frequency: "Mensal",
    direction: "maior_melhor", target: null, assumptions: null, exclusions: null, source_tables: "fato_vendas + fato_estoque_diario", lineage: null, quality_checks: null, consumers: "Compras, Financeiro",
  },
  {
    key: "aging_estoque", name: "Aging de estoque", code: "EST-005", domain: "estoque",
    definition: "Distribuição do estoque por tempo desde a última entrada/venda.", business_question: "Quanto do estoque está parado e corre risco de obsolescência?",
    formula: "Σ estoque a custo por faixa (0–30, 31–90, 91–180, >180 dias sem venda)", numerator: null, denominator: null, unit: "R$ / %", granularity: "SKU × local", frequency: "Semanal",
    direction: "menor_melhor", target: "< 10% do estoque acima de 180 dias", assumptions: "Referência = data da última venda (alternativa: data de entrada — declarar qual).",
    exclusions: null, source_tables: "fato_estoque_diario + fato_vendas + movimentações de entrada", lineage: null, quality_checks: null, consumers: "Compras, Financeiro",
  },
  {
    key: "otif", name: "OTIF (On Time In Full)", code: "LOG-001", domain: "logistica",
    definition: "Percentual de pedidos entregues no prazo prometido e com a quantidade completa.",
    business_question: "Estamos cumprindo a promessa de entrega?",
    formula: "Pedidos entregues até a data prometida E com 100% dos itens ÷ Pedidos com entrega prevista no período",
    numerator: "Pedidos no prazo e completos", denominator: "Pedidos com entrega prevista", unit: "%", granularity: "Dia × transportadora × região", frequency: "Diária",
    direction: "maior_melhor", target: "≥ 95%",
    assumptions: "Data prometida = data informada ao cliente no checkout/pedido (não a data da transportadora). Entrega parcial = falha.",
    exclusions: "Pedidos cancelados pelo cliente antes da expedição.", source_tables: "TMS/rastreio: eventos de entrega + ERP: pedidos (data prometida, itens)",
    lineage: null, quality_checks: "Pedidos sem data de entrega real; datas de entrega anteriores à expedição.", consumers: "Logística, SAC, Comercial",
  },
  {
    key: "lead_time_entrega", name: "Lead time de entrega", code: "LOG-002", domain: "logistica",
    definition: "Tempo entre a aprovação do pedido e a entrega ao cliente.", business_question: "Quanto tempo o cliente espera?",
    formula: "Média (ou P90) de [data entrega − data aprovação do pedido]", numerator: null, denominator: null, unit: "dias", granularity: "Pedido × transportadora × região", frequency: "Diária",
    direction: "menor_melhor", target: null, assumptions: "Declarar se conta dias úteis ou corridos. Reportar P90 além da média.", exclusions: null,
    source_tables: "ERP pedidos + TMS eventos", lineage: null, quality_checks: null, consumers: "Logística, E-commerce",
  },
  {
    key: "custo_frete_receita", name: "Custo de frete sobre receita", code: "LOG-003", domain: "logistica",
    definition: "Peso do frete de saída na receita líquida.", business_question: "O frete está comendo a margem?",
    formula: "Σ custo de frete (CT-e/faturas) ÷ Faturamento líquido", numerator: "Custo de frete", denominator: "Faturamento líquido", unit: "%", granularity: "Mês × transportadora × região × canal", frequency: "Mensal",
    direction: "menor_melhor", target: null, assumptions: "Custo pela fatura conciliada (não pela cotação). Frete cobrado do cliente reportado separado.",
    exclusions: "Frete de transferência entre CDs (reportar em KPI próprio).", source_tables: "CT-e / faturas de transportadoras + fato_vendas", lineage: null,
    quality_checks: "CT-e sem pedido vinculado; divergência cotação × fatura.", consumers: "Logística, Financeiro",
  },
  {
    key: "produtividade_separacao", name: "Produtividade de separação", code: "LOG-004", domain: "logistica",
    definition: "Linhas/itens separados por hora-homem no CD.", business_question: "O CD tem capacidade para o volume?",
    formula: "Linhas separadas ÷ horas trabalhadas na separação", numerator: "Linhas separadas", denominator: "Horas-homem", unit: "linhas/h", granularity: "Dia × turno × operador", frequency: "Diária",
    direction: "maior_melhor", target: null, assumptions: null, exclusions: null, source_tables: "WMS: tarefas de picking + ponto/escala", lineage: null, quality_checks: null, consumers: "Operações do CD",
  },
  {
    key: "lead_time_fornecedor", name: "Lead time de fornecedor", code: "CMP-001", domain: "compras",
    definition: "Tempo entre emissão do pedido de compra e recebimento no CD.", business_question: "Com quanta antecedência precisamos comprar?",
    formula: "Média/P90 de [data recebimento − data emissão do PC]", numerator: null, denominator: null, unit: "dias", granularity: "Fornecedor × SKU", frequency: "Mensal",
    direction: "menor_melhor", target: null, assumptions: "Recebimento = entrada da NF no WMS/ERP.", exclusions: null, source_tables: "ERP: pedidos de compra + notas de entrada", lineage: null, quality_checks: null, consumers: "Compras",
  },
  {
    key: "fill_rate_fornecedor", name: "Fill rate de fornecedor", code: "CMP-002", domain: "compras",
    definition: "Percentual da quantidade pedida efetivamente entregue pelo fornecedor.", business_question: "O fornecedor entrega o que pedimos?",
    formula: "Quantidade recebida ÷ Quantidade pedida", numerator: "Qtd recebida", denominator: "Qtd pedida", unit: "%", granularity: "Fornecedor × mês", frequency: "Mensal",
    direction: "maior_melhor", target: "≥ 95%", assumptions: "Excesso de entrega não compensa falta de outro item.", exclusions: null, source_tables: "ERP: PC × NF de entrada", lineage: null, quality_checks: null, consumers: "Compras",
  },
  {
    key: "conversao", name: "Taxa de conversão (e-commerce)", code: "ECM-001", domain: "ecommerce",
    definition: "Percentual de sessões que geram pedido.", business_question: "O site transforma visita em venda?",
    formula: "Pedidos ÷ Sessões", numerator: "Pedidos", denominator: "Sessões", unit: "%", granularity: "Dia × canal de aquisição × dispositivo", frequency: "Diária",
    direction: "maior_melhor", target: null, assumptions: "Pedidos da plataforma (não faturados) — declarar. Sessões do GA4.", exclusions: "Tráfego interno/bots.",
    source_tables: "GA4 + plataforma de e-commerce (pedidos)", lineage: null, quality_checks: "Pedidos na plataforma × pedidos no GA4 (divergência > 5%).", consumers: "E-commerce, Marketing",
  },
  {
    key: "roi_campanha", name: "ROI de campanha", code: "ECM-002", domain: "ecommerce",
    definition: "Retorno da campanha considerando custo de mídia e custo do produto.", business_question: "A campanha dá lucro ou só volume?",
    formula: "(Margem bruta atribuída − Custo de mídia) ÷ Custo de mídia", numerator: "Margem atribuída − mídia", denominator: "Custo de mídia", unit: "%", granularity: "Campanha × semana", frequency: "Semanal",
    direction: "maior_melhor", target: null, assumptions: "Modelo de atribuição declarado (último clique, janela de 7 dias). Custo de produto do FP&A.",
    exclusions: null, source_tables: "Google Ads/Meta (custo) + plataforma (pedidos com UTM) + custo FP&A", lineage: null,
    quality_checks: "Pedidos sem UTM; campanhas sem custo.", consumers: "Marketing, RGM",
  },
  {
    key: "taxa_devolucao", name: "Taxa de devolução", code: "ECM-003", domain: "ecommerce",
    definition: "Percentual de itens vendidos que retornam.", business_question: "Quanto da venda volta — e por quê?",
    formula: "Itens devolvidos ÷ Itens vendidos (mesma safra de venda)", numerator: "Itens devolvidos", denominator: "Itens vendidos", unit: "%", granularity: "Mês × categoria × motivo", frequency: "Mensal",
    direction: "menor_melhor", target: null, assumptions: "Safra: devolução associada ao mês da venda original.", exclusions: null, source_tables: "ERP devoluções + SAC motivos", lineage: null, quality_checks: "Devoluções sem motivo categorizado.", consumers: "E-commerce, Qualidade, SAC",
  },
  {
    key: "completude_cadastro", name: "Completude de cadastro", code: "CAD-001", domain: "cadastro",
    definition: "Percentual de cadastros ativos (itens, clientes ou fornecedores) com todos os campos obrigatórios preenchidos e válidos.", business_question: "O cadastro sustenta fiscal, operação e relatórios?",
    formula: "Cadastros ativos com campos obrigatórios válidos ÷ Cadastros ativos", numerator: "Cadastros completos", denominator: "Cadastros ativos", unit: "%", granularity: "Campo × tipo de cadastro", frequency: "Semanal",
    direction: "maior_melhor", target: "100% nos mais usados", assumptions: "Campos obrigatórios definidos por tipo de cadastro (ex.: itens — NCM, EAN, custo; clientes — CPF/CNPJ, endereço).", exclusions: null,
    source_tables: "ERP: tabelas de cadastro", lineage: null, quality_checks: "Documento inválido (dígito verificador); código fiscal inexistente.", consumers: "Cadastro, Fiscal, Operações",
  },
  // ------------------------------------------------ núcleo universal
  {
    key: "taxa_conversao_propostas", name: "Taxa de conversão de propostas", code: "COM-003", domain: "comercial",
    definition: "Percentual das propostas/oportunidades que viram venda ou contrato.", business_question: "Quanto do esforço comercial vira receita?",
    formula: "Propostas ganhas ÷ Propostas encerradas (ganhas + perdidas) no período", numerator: "Propostas ganhas", denominator: "Propostas encerradas", unit: "%", granularity: "Mês × vendedor × segmento", frequency: "Mensal",
    direction: "maior_melhor", target: null, assumptions: "Proposta conta no mês em que foi encerrada, não no mês de envio.", exclusions: "Propostas canceladas pelo próprio time (duplicadas, erro).",
    source_tables: "CRM: oportunidades com status e data de encerramento", lineage: null, quality_checks: "Propostas abertas há mais de 90 dias sem atualização; propostas sem valor.", consumers: "Comercial, Diretoria",
  },
  {
    key: "inadimplencia", name: "Inadimplência", code: "FIN-003", domain: "financeiro",
    definition: "Percentual do valor a receber vencido há mais de X dias.", business_question: "Quanto do que vendemos não está entrando no caixa?",
    formula: "Títulos vencidos há mais de 30 dias ÷ Total de títulos a receber", numerator: "Valor vencido > 30 dias", denominator: "Carteira a receber", unit: "%", granularity: "Mês × cliente × unidade", frequency: "Semanal",
    direction: "menor_melhor", target: null, assumptions: "Corte de 30 dias (ajustar ao negócio). Renegociações contam como adimplentes a partir da nova data.", exclusions: "Títulos em disputa judicial — reportar à parte.",
    source_tables: "ERP financeiro: contas a receber", lineage: null, quality_checks: "Títulos sem vencimento; baixas sem data.", consumers: "Financeiro, Comercial, Diretoria",
  },
  {
    key: "prazo_fechamento", name: "Prazo de fechamento gerencial", code: "FIN-004", domain: "financeiro",
    definition: "Dias úteis entre o fim do mês e a publicação do resultado gerencial.", business_question: "Quanto tempo a gestão espera para saber o resultado do mês?",
    formula: "Data de publicação da DRE gerencial − último dia útil do mês (em dias úteis)", numerator: null, denominator: null, unit: "dias úteis", granularity: "Mês", frequency: "Mensal",
    direction: "menor_melhor", target: null, assumptions: "Conta a publicação da versão aprovada pela diretoria.", exclusions: null,
    source_tables: "Registro de fechamento (data de publicação)", lineage: null, quality_checks: "Republicações após a data oficial.", consumers: "Diretoria, Controladoria",
  },
  {
    key: "turnover", name: "Turnover", code: "RH-001", domain: "pessoas",
    definition: "Rotatividade de colaboradores no período.", business_question: "Estamos retendo as pessoas?",
    formula: "((Admissões + Desligamentos) ÷ 2) ÷ Quadro médio do período", numerator: "Média de admissões e desligamentos", denominator: "Quadro médio", unit: "%", granularity: "Mês × área × unidade", frequency: "Mensal",
    direction: "menor_melhor", target: null, assumptions: "Quadro médio = (início + fim do período) ÷ 2. Definir se inclui estagiários e temporários.", exclusions: "Transferências entre unidades.",
    source_tables: "Sistema de folha: admissões, desligamentos, quadro", lineage: null, quality_checks: "Desligamento sem data; colaborador ativo sem área.", consumers: "RH, Diretoria, Gestores",
  },
  {
    key: "absenteismo", name: "Absenteísmo", code: "RH-002", domain: "pessoas",
    definition: "Percentual de horas previstas não trabalhadas por ausências.", business_question: "Quanto da capacidade planejada perdemos com ausências?",
    formula: "Horas de ausência ÷ Horas previstas de trabalho", numerator: "Horas de ausência", denominator: "Horas previstas", unit: "%", granularity: "Mês × área × tipo de ausência", frequency: "Mensal",
    direction: "menor_melhor", target: null, assumptions: "Definir quais ausências contam (faltas, atestados; férias não contam).", exclusions: "Férias, licenças programadas.",
    source_tables: "Ponto eletrônico + folha", lineage: null, quality_checks: "Dias sem marcação de ponto; atestados sem lançamento.", consumers: "RH, Gestores",
  },
  {
    key: "headcount", name: "Quadro de colaboradores", code: "RH-003", domain: "pessoas",
    definition: "Número de colaboradores ativos no último dia do período.", business_question: "Quantas pessoas temos, onde e em que função?",
    formula: "Contagem de colaboradores ativos na data de corte", numerator: null, denominator: null, unit: "pessoas", granularity: "Mês × área × unidade × vínculo", frequency: "Mensal",
    direction: "faixa", target: null, assumptions: "Definir vínculos incluídos (CLT, PJ, estágio, temporário).", exclusions: null,
    source_tables: "Sistema de folha", lineage: null, quality_checks: "Quadro da folha × ponto × gerencial deve bater.", consumers: "RH, Financeiro, Diretoria",
  },
  {
    key: "cumprimento_prazo", name: "Cumprimento de prazo com o cliente", code: "OPS-001", domain: "operacoes",
    definition: "Percentual de entregas/atendimentos concluídos dentro do prazo prometido.", business_question: "Estamos cumprindo o que prometemos ao cliente?",
    formula: "Entregas no prazo ÷ Entregas concluídas", numerator: "Entregas no prazo", denominator: "Entregas concluídas", unit: "%", granularity: "Semana × cliente × tipo de serviço", frequency: "Semanal",
    direction: "maior_melhor", target: null, assumptions: "Prazo = data prometida no pedido/contrato (não a data replanejada). Tolerância definida por tipo.", exclusions: "Atrasos causados pelo cliente, com registro.",
    source_tables: "Sistema da operação: data prometida e data de conclusão", lineage: null, quality_checks: "Entregas sem data prometida; conclusão antes do início.", consumers: "Operações, Comercial, Diretoria",
  },
  {
    key: "taxa_retrabalho", name: "Taxa de retrabalho", code: "OPS-002", domain: "operacoes",
    definition: "Percentual de entregas/atendimentos que precisaram ser refeitos.", business_question: "Quanto do nosso esforço é gasto refazendo?",
    formula: "Entregas com retrabalho ÷ Entregas concluídas", numerator: "Entregas com retrabalho", denominator: "Entregas concluídas", unit: "%", granularity: "Mês × causa × equipe", frequency: "Mensal",
    direction: "menor_melhor", target: null, assumptions: "Retrabalho registrado com causa de lista fechada.", exclusions: null,
    source_tables: "Registro de ocorrências + sistema da operação", lineage: null, quality_checks: "Ocorrências sem causa.", consumers: "Operações, Qualidade",
  },
  {
    key: "tempo_atendimento", name: "Tempo médio de atendimento", code: "OPS-003", domain: "operacoes",
    definition: "Tempo médio entre a abertura e a conclusão de um atendimento/solicitação.", business_question: "Quanto o cliente espera por uma solução?",
    formula: "Σ (conclusão − abertura) ÷ Nº de atendimentos concluídos", numerator: "Tempo total", denominator: "Atendimentos concluídos", unit: "horas", granularity: "Semana × canal × tipo", frequency: "Semanal",
    direction: "menor_melhor", target: null, assumptions: "Conta tempo corrido (ou útil — definir). Reaberturas somam ao original.", exclusions: "Atendimentos cancelados.",
    source_tables: "Sistema de atendimento / chamados", lineage: null, quality_checks: "Atendimentos sem data de conclusão há mais de 30 dias.", consumers: "Atendimento, Operações",
  },
  // ------------------------------------------------ módulos por setor
  {
    key: "oee", name: "OEE (eficiência global do equipamento)", code: "PRD-001", domain: "producao",
    definition: "Disponibilidade × desempenho × qualidade de uma linha ou equipamento.", business_question: "Quanto da capacidade instalada vira produto bom?",
    formula: "Disponibilidade × Performance × Qualidade", numerator: null, denominator: null, unit: "%", granularity: "Dia × linha × turno", frequency: "Diária",
    direction: "maior_melhor", target: null, assumptions: "Paradas planejadas saem do tempo disponível. Tempo padrão por produto definido pela engenharia.", exclusions: "Testes e setups de novos produtos (reportar à parte).",
    source_tables: "Apontamento de produção + paradas", lineage: null, quality_checks: "Turnos sem apontamento; produção acima da capacidade teórica.", consumers: "Produção, Engenharia, Diretoria",
  },
  {
    key: "indice_refugo", name: "Índice de refugo", code: "PRD-002", domain: "producao",
    definition: "Percentual da produção descartada ou reprovada.", business_question: "Quanto do que produzimos é perdido?",
    formula: "Quantidade refugada ÷ Quantidade produzida", numerator: "Refugo", denominator: "Produção total", unit: "%", granularity: "Semana × linha × produto × causa", frequency: "Semanal",
    direction: "menor_melhor", target: null, assumptions: "Retrabalho aprovado não conta como refugo.", exclusions: null,
    source_tables: "Apontamento de produção + registro de não conformidades", lineage: null, quality_checks: "Refugo apontado × não conformidades registradas.", consumers: "Produção, Qualidade",
  },
  {
    key: "taxa_utilizacao", name: "Taxa de utilização (horas faturáveis)", code: "PRJ-001", domain: "projetos",
    definition: "Percentual das horas disponíveis da equipe dedicadas a trabalho faturável.", business_question: "A equipe está alocada em trabalho que gera receita?",
    formula: "Horas faturáveis apontadas ÷ Horas disponíveis", numerator: "Horas faturáveis", denominator: "Horas disponíveis", unit: "%", granularity: "Mês × pessoa × área", frequency: "Mensal",
    direction: "faixa", target: null, assumptions: "Horas disponíveis descontam férias e feriados.", exclusions: "Horas internas (treinamento, pré-venda) — reportar à parte.",
    source_tables: "Apontamento de horas + cadastro de colaboradores", lineage: null, quality_checks: "Semanas sem apontamento; horas acima da jornada.", consumers: "Operações, Financeiro, Diretoria",
  },
  {
    key: "margem_contrato", name: "Margem por contrato", code: "PRJ-002", domain: "projetos",
    definition: "Resultado de cada contrato/projeto após custos diretos de horas e despesas.", business_question: "Quais contratos dão lucro de verdade?",
    formula: "(Receita do contrato − custo das horas − despesas diretas) ÷ Receita do contrato", numerator: "Resultado do contrato", denominator: "Receita do contrato", unit: "%", granularity: "Mês × contrato", frequency: "Mensal",
    direction: "maior_melhor", target: null, assumptions: "Custo/hora = salário + encargos ÷ horas disponíveis.", exclusions: "Despesas administrativas rateadas (ver regra de rateio).",
    source_tables: "Apontamento de horas + faturamento + despesas", lineage: null, quality_checks: "Contratos com receita e sem horas apontadas.", consumers: "Financeiro, Diretoria",
  },
];
